Checking the latest version

diff --git a/assets/check b/assets/check
--- a/assets/check
+++ b/assets/check
@@ -1,3 +1,18 @@
 #!/bin/sh
+# vim: set ft=sh
 
-echo "[]"
+set -e
+
+exec 3>&1 # make stdout available as fd 3 for the result
+exec 1>&2 # redirect all output to stderr for logging
+
+source $(dirname $0)/common.sh
+
+LATEST_RESULTS=$(curl -sSL -u "$user:$password" "$url/api/versions/$path")
+
+if echo $LATEST_RESULTS | jq -e 'has("errors")' > /dev/null; then
+	echo $LATEST_RESULTS | jq -c '.errors[0]'
+	echo "[]" >&3
+else 
+	echo $LATEST_RESULTS | jq -c '[{version: .version}]' >&3
+fi
diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -1,3 +1,48 @@
 #!/bin/sh
+# vim: set ft=sh
 
-echo '{"version":{"ref":"none"}}'
+set -e
+
+exec 3>&1 # make stdout available as fd 3 for the result
+exec 1>&2 # redirect all output to stderr for logging
+
+destination=$1
+
+if [ -z "$destination" ]; then
+  echo "usage: $0 <path/to/destination>"
+  exit 1
+fi
+
+source $(dirname $0)/common.sh
+
+cd $destination
+
+version=$(jq -r '.version.version // ""' < $request_payload)
+if [ -z "$version" ]; then
+	echo "invalid request (missing version)"
+	exit 1
+fi
+
+explode=$(jq -r '.params.explode // "false"' < $request_payload)
+
+pattern=$(echo $regexp | sed -e 's/(.*)/*/')
+results=$(jfrog rt dl $path/$pattern --props="version=$version" --recursive=false --flat=true $jfrog_args)
+
+if ! echo "$results" | grep -q "Downloaded 1 artifact"; then
+	echo "Failed to get any artifacts:"
+	echo $results
+	exit 1
+fi
+
+filename=$(echo $regexp | sed -e 's/(.*)/'"$version"'/')
+if [ "$explode" = "true" ]; then
+	tar -xvf $filename
+	rm $filename
+fi
+
+echo '{"version": { "version": "'$version'"}, "metadata": []}' >&3
+
+
+
+
+
diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -1,3 +1,53 @@
 #!/bin/sh
+# vim: set ft=sh
 
-echo '{"version":{"ref":"none"}}'
+set -e
+
+exec 3>&1 # make stdout available as fd 3 for the result
+exec 1>&2 # redirect all output to stderr for logging
+
+source=$1
+
+if [ -z "$source" ]; then
+  echo "usage: $0 <path/to/source>"
+  exit 1
+fi
+
+cd $source
+
+
+# Parse source settings
+source $(dirname $0)/common.sh
+
+jfrog_args="--url=$url --user=$user --password=$password"
+
+cd $source
+
+file=$(jq -r '.params.file // ""' < $request_payload)
+if [ -z "$file" ]; then
+	echo "invalid request (missing file)"
+	exit 1
+fi
+
+filename=$(find $file -type f -exec basename {} \;)
+if [ -z "$filename" ]; then
+	echo "couldnt find file $file"
+	exit 1
+fi
+
+fileversion=$(echo $filename | sed -E "s/$regexp/\1/")
+if [ -z "$fileversion" ]; then
+	echo "couldnt find version in $filename"
+	exit 1
+fi
+
+# artifactory_upload path/to/file version
+jfrog rt upload $file "$path/$filename" --props="version=$fileversion" $jfrog_args
+
+
+echo '{"version": { "version": "'$version'"}, "metadata": []}' >&3
+
+
+
+
+
